from Tkinter import *
tk=Tk()
tk.overrideredirect(True)
tk.geometry("{0}x{1}+0+0".format(tk.winfo_screenwidth(),tk.winfo_screenheight()))
tk.focus_set()
tk.bind("<Escape>", lambda e: e.widget.quit())
main_frame= Frame(tk)
main_frame.grid(row=3)
frame1 = Frame(main_frame,bg="orange",width=800,height=90)
frame2 = Frame(main_frame,bg="blue",width=70,height=300)
frame3 = Frame(main_frame,bg="green",width=300,height=300)
frame4 = Frame(main_frame,bg="blue",width=60,height=300)
frame5 = Frame(main_frame,bg="green",width=300,height=300)
frame6 = Frame(main_frame,bg="blue",width=70,height=300)
frame7 = Frame(main_frame,bg="orange",width=800,height=90)


frame1.grid(row=1,column=1,columnspan=5)
frame2.grid(row=2,column=1)
frame3.grid(row=2,column=2)
frame4.grid(row=2,column=3)
frame5.grid(row=2,column=4)
frame6.grid(row=2,column=5)
frame7.grid(row=3,column=1,columnspan=5)
frame3.pack_propagate(0)
frame5.pack_propagate(0)
btn1= Button(frame3,text='Next',width=30,height=30)
btn1.pack(side='left')
btn2= Button(frame5,text='Previous',width=30,height=30)
btn2.pack(side='right')
tk.mainloop()

